version: "2"
services:
  front-envoy-one:
    build:
      context: ../apps
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    environment:
      - PROXY_NAME=one
    expose:
      # Expose ports 80 (for general traffic) and 8001 (for the admin server)
      - "80"
      - "8001"
    ports:
      # Map the host port 8010 to container port 80, and the host port 8001 to container port 8001
      - "8010:80"
      - "8001:8001"
  front-envoy-two:
    build:
      context: ../apps
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    environment:
      - PROXY_NAME=two
    expose:
      # Expose ports 80 (for general traffic) and 8001 (for the admin server)
      - "80"
      - "8001"
    ports:
      # Map the host port 8020 to container port 80, and the host port 8002 to container port 8001
      - "8020:80"
      - "8002:8001"
  service_blue:
    build:
      context: ../apps
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy-fault-injection-delay.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_blue
    environment:
      - SERVICE_NAME=blue
    expose:
      - "80"
  service_green:
    build:
      context: ../apps
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_green
    environment:
      - SERVICE_NAME=green
    expose:
      - "80"
  service_red:
    build:
      context: ../apps
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy-fault-injection-abort.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_red
    environment:
      - SERVICE_NAME=red
    expose:
      - "80"
networks:
  envoymesh: {}

