FROM envoyproxy/envoy:v1.11.1

RUN apt-get update && apt-get -q install -y \
    python3 \
    python-pip \
    python3-pip \
    curl
RUN python3 --version && pip3 --version
RUN pip3 install -q Flask==0.11.1 requests==2.18.4

RUN mkdir /code
ADD service.py /code
ADD start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
