FROM envoyproxy/envoy:v1.11.1

RUN apt-get update && apt-get -q install -y \
    curl
ADD start_front_proxy.sh /usr/local/bin/start_front_proxy.sh
RUN chmod u+x /usr/local/bin/start_front_proxy.sh
ENTRYPOINT /usr/local/bin/start_front_proxy.sh
